/*

    CRIE UM CRUD UTILIZANDO ROUTER, CONTROLLER, MODEL E ACESSO AO BANCO MYSQL


    EMPRESA SERÁ UMA FARMÁCIA QUE POSSUI AS FUNCIONALIDADES
       
    - CRIAÇÃO, EDIÇÃO LISTAGEM E REMOVER MEDICAMENTO

    - REMOVER ESTOQUE DE PRODUTOS

    - ADICIONAR ESTOQUE DE PRODUTOS

    FARMACIA POSSUI UMA TABELA DE MEDICAMENTOS
 

    MEDICAMENTO POSSUI OS SEGUINTE ATRIBUTOS
    NOME
    DESCRICAO
    ESTOQUE
    VENCIMENTO
    TIPO DE PEDICAMENTO
    CREATED_AT
    UPDATED_AT

    CRIAR TABELA COM O NOME RETIRADA_MEDICAMENTOS
    ESTOQUE POSSUI OS SEGUINTES ATRIBUTOS

    ID_MEDICAMENTO
    QUANTIDADE_RETIRADA

    CRIAR TABELA COM O NOME ABASTECIMENTO_MEDICAMENTOS
    ESTOQUE POSSUI OS SEGUINTES ATRIBUTOS

    ID_MEDICAMENTOS
    QUANTIDADE_ABASTECIDA
    CREATED_AT
    
*/